# Generated by Django 2.2 on 2022-12-06 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Result_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_student', models.CharField(blank=True, max_length=100)),
                ('ref', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('verified', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('Class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Level', to='Result_portal.Class')),
                ('Payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exactamount', to='Payment_portal.Amount')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
