# Generated by Django 2.2 on 2022-12-18 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Class',
            new_name='student_class',
        ),
    ]
