# Generated by Django 2.2 on 2023-03-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_portal', '0002_auto_20221217_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='amount',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='Payment_type',
        ),
        migrations.AddField(
            model_name='payment',
            name='Payment_type',
            field=models.ManyToManyField(related_name='payments', to='Payment_portal.Amount'),
        ),
    ]
