# Generated by Django 2.2 on 2023-03-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_portal', '0005_auto_20230308_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
