# Generated by Django 2.2 on 2022-12-05 22:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnumber', models.CharField(blank=True, max_length=300)),
                ('Questions', models.CharField(blank=True, max_length=300)),
                ('Answer', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Aims_and_Objectives', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Vision', models.TextField(blank=True, null=True)),
                ('Mission', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profileimage', models.ImageField(blank=True, upload_to='assets')),
                ('Profilename', models.CharField(blank=True, max_length=300)),
                ('Role', models.CharField(blank=True, max_length=300)),
                ('Phonenumber', models.CharField(blank=True, max_length=300)),
                ('Emailaddress', models.CharField(blank=True, max_length=300)),
                ('Facebookpage', models.CharField(blank=True, max_length=300)),
                ('Twitterpage', models.CharField(blank=True, max_length=300)),
                ('Whatsapp', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(upload_to='assets')),
                ('Description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Schoolid', models.IntegerField()),
                ('Schoollogo', models.ImageField(blank=True, upload_to='assets')),
                ('Schoolname', models.CharField(blank=True, max_length=300)),
                ('SchoolPhonenumber', models.CharField(blank=True, max_length=300)),
                ('Schoolmotto', models.CharField(blank=True, max_length=300)),
                ('Schoollocation', models.CharField(blank=True, max_length=300)),
                ('Facebookpage', models.CharField(blank=True, max_length=300)),
                ('Twitterpage', models.CharField(blank=True, max_length=300)),
                ('Whatsapp', models.CharField(blank=True, max_length=300)),
                ('Emailaddress', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flier', models.ImageField(blank=True, upload_to='assets')),
                ('Eventtitle', models.CharField(blank=True, max_length=300)),
                ('EventTopic', models.CharField(blank=True, max_length=300)),
                ('Eventspeaker_Chairman', models.CharField(blank=True, max_length=300)),
                ('Eventdate', models.CharField(blank=True, max_length=300)),
                ('Eventtime', models.CharField(blank=True, max_length=300)),
                ('Eventvenue', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
