# Generated by Django 2.2 on 2022-12-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Headshot',
            field=models.ImageField(blank=True, default='assets/default.png', upload_to='assets'),
        ),
    ]
