# Generated by Django 2.2 on 2023-11-23 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_topteachers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopTeachers',
            new_name='TopTeacher',
        ),
    ]
