# Generated by Django 2.2 on 2022-12-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20221229_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingevents',
            name='Flier',
            field=models.ImageField(blank=True, default='assets/No image.svg', upload_to='assets'),
        ),
    ]
