# Generated by Django 2.2 on 2022-12-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20221230_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentsReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profileimage', models.ImageField(blank=True, default='assets/parents image.png', upload_to='assets')),
                ('Name', models.CharField(blank=True, max_length=300)),
                ('Occupation', models.CharField(blank=True, max_length=300)),
                ('Review', models.TextField(blank=True, max_length=40)),
            ],
        ),
    ]
