# Generated by Django 2.2 on 2022-12-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_parentsreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentsreview',
            name='Review',
            field=models.TextField(blank=True),
        ),
    ]
