# Generated by Django 2.2 on 2023-03-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20230104_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentsreview',
            name='Profileimage',
            field=models.ImageField(blank=True, upload_to='assets/parentsProfileimages'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='Photo',
            field=models.ImageField(upload_to='assets/photogallery'),
        ),
        migrations.AlterField(
            model_name='school',
            name='Schoollogo',
            field=models.ImageField(blank=True, upload_to='assets/Schoollogo'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Headshot',
            field=models.ImageField(blank=True, upload_to='assets/TeachersProfileimages'),
        ),
        migrations.AlterField(
            model_name='upcomingevents',
            name='Flier',
            field=models.ImageField(blank=True, upload_to='assets/eventfliers'),
        ),
    ]
