# Generated by Django 2.2 on 2023-03-12 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Result_portal', '0008_students_pin_and_id_student_password'),
        ('Home', '0008_auto_20230308_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTeachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Form_teachers_Name', models.CharField(blank=True, max_length=200)),
                ('Form_teachers_Headshot', models.ImageField(blank=True, upload_to='assets/TeachersProfileimages')),
                ('Form_teachers_id', models.CharField(blank=True, max_length=200)),
                ('Form_teachers_password', models.CharField(blank=True, max_length=200)),
                ('Class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Result_portal.Class')),
            ],
        ),
    ]
