# Generated by Django 2.2 on 2023-03-13 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Result_portal', '0008_students_pin_and_id_student_password'),
        ('Home', '0009_formteachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Class_assigned',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Classes_assigned',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Result_portal.Class'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formteachers',
            name='Class',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Result_portal.Class'),
        ),
    ]
