# Generated by Django 2.2 on 2023-03-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_auto_20230313_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Role',
            field=models.CharField(blank=True, default='Teacher', max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Subject',
            field=models.CharField(help_text='if more than one , add it comma-separated', max_length=200),
        ),
    ]
