# Generated by Django 2.2 on 2023-04-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_auto_20230313_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='questionnumber',
            field=models.CharField(blank=True, help_text='use alphabets like one , two & three', max_length=300),
        ),
    ]
