# Generated by Django 2.2 on 2023-10-28 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Result_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200)),
                ('Phone_number', models.CharField(blank=True, max_length=200)),
                ('Email', models.EmailField(blank=True, max_length=200)),
                ('Role', models.CharField(blank=True, default='Teacher', max_length=200)),
                ('Subject', models.CharField(help_text='if more than one , add it comma-separated', max_length=200)),
                ('teachers_id', models.CharField(blank=True, max_length=200)),
                ('teachers_password', models.CharField(blank=True, max_length=200)),
                ('Headshot', models.ImageField(blank=True, upload_to='assets/TeachersProfileimages')),
                ('Classes_assigned', models.ManyToManyField(to='Result_portal.Class')),
            ],
        ),
        migrations.CreateModel(
            name='FormTeachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Form_teachers_Name', models.CharField(blank=True, max_length=200)),
                ('Form_teachers_Headshot', models.ImageField(blank=True, upload_to='assets/TeachersProfileimages')),
                ('Form_teachers_id', models.CharField(blank=True, max_length=200)),
                ('Form_teachers_password', models.CharField(blank=True, max_length=200)),
                ('Class', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Result_portal.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('form_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teachers_Portal.FormTeachers')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Result_portal.Students_Pin_and_ID')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
