# Generated by Django 2.2 on 2023-10-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers_Portal', '0003_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Role',
            field=models.CharField(blank=True, choices=[('Teacher', 'Teacher'), ('Formteacher', 'Formteacher'), ('Admin', 'Admin')], default='Teacher', max_length=200),
        ),
    ]
