# Generated by Django 2.2 on 2023-10-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers_Portal', '0004_auto_20231029_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teachers_password',
        ),
        migrations.AddField(
            model_name='teacher',
            name='FirstName',
            field=models.CharField(blank=True, default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='LastName',
            field=models.CharField(blank=True, default='None', max_length=200),
        ),
    ]
