# Generated by Django 2.2 on 2023-03-13 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0009_formteachers'),
        ('Result_portal', '0008_students_pin_and_id_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CBT.Exam')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Result_portal.Class')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Result_portal.Students_Pin_and_ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('code', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CBT.Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Result_portal.Students_Pin_and_ID')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No Subject', max_length=255)),
                ('exam_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CBT.ExamClass')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CBT.Subject')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Home.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=1000)),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CBT.QuestionSet')),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CBT.Exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CBT.Question')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CBT.Answer')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CBT.Exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CBT.ExamQuestion')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CBT.Question'),
        ),
    ]
