# Generated by Django 2.2 on 2023-03-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CBT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examclass',
            name='students',
        ),
    ]
