# Generated by Django 2.2 on 2023-03-13 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CBT', '0002_remove_examclass_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionset',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Teacher'),
        ),
    ]
