# Generated by Django 2.2 on 2023-11-09 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CBT', '0003_auto_20231109_1418'),
    ]

    operations = [
    ]
