# Generated by Django 2.2 on 2023-06-14 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Result_portal', '0010_auto_20230416_0105'),
        ('CBT', '0003_auto_20230313_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBTQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_Question_Link', models.CharField(max_length=300)),
                ('StudentClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Result_portal.Class')),
            ],
        ),
    ]
