# Generated by Django 2.2 on 2023-11-09 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CBT', '0004_auto_20231109_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsetgroup',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
