# Generated by Django 2.2 on 2023-11-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CBT', '0005_questionsetgroup_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionSetGroup',
        ),
    ]
