# Generated by Django 2.2 on 2023-11-09 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CBT', '0006_delete_questionsetgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No Subject', max_length=255)),
                ('date', models.DateField()),
                ('questionsets', models.ManyToManyField(related_name='questionsets', to='CBT.QuestionSet')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CBT.Test')),
            ],
        ),
    ]
