# Generated by Django 2.2 on 2023-11-09 16:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Result_portal', '0005_auto_20231103_2309'),
        ('Teachers_Portal', '0005_auto_20231030_0044'),
        ('CBT', '0008_auto_20231109_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerId', models.CharField(default='None', max_length=100)),
                ('answertext', models.CharField(default='None', max_length=255)),
                ('isCorrect', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionId', models.CharField(default='None', max_length=100)),
                ('questiontext', ckeditor.fields.RichTextField(default='None', null=True)),
                ('questionMark', models.IntegerField(blank=True, default=0)),
                ('required', models.BooleanField(default=True)),
                ('answers', models.ManyToManyField(to='CBT.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examTime', models.IntegerField(blank=True, default=0)),
                ('ExamClass', models.ManyToManyField(blank=True, to='Result_portal.Class')),
                ('questions', models.ManyToManyField(blank=True, to='CBT.Question')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Result_portal.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teachers_Portal.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TestSetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=255)),
                ('timeUsedForTest', models.IntegerField(blank=True, default=0)),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Result_portal.Students_Pin_and_ID')),
                ('test', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='CBT.Test')),
                ('testClass', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Result_portal.Class')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testTotalScore', models.IntegerField(blank=True, default=0)),
                ('testSetGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CBT.TestSetGroup')),
                ('testSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Result_portal.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No Subject', max_length=255)),
                ('date', models.DateField()),
                ('questionsets', models.ManyToManyField(related_name='questionsets', to='CBT.QuestionSet')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CBT.Test')),
            ],
        ),
    ]
