# Generated by Django 2.2 on 2023-11-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBT', '0010_auto_20231113_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsetgroup',
            name='questionsets',
            field=models.ManyToManyField(blank=True, related_name='questionsets', to='CBT.QuestionSet'),
        ),
    ]
