# Generated by Django 2.2 on 2022-12-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=100)),
                ('lastName', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('lGA', models.CharField(blank=True, max_length=100)),
                ('state_of_Origin', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('school_attended', models.CharField(blank=True, max_length=100)),
                ('Last_Class_passed', models.CharField(blank=True, max_length=100)),
                ('common_Ent_Exam_Number', models.CharField(blank=True, max_length=100, null=True)),
                ('agg_Score', models.CharField(blank=True, max_length=100, null=True)),
                ('class_applying_for', models.CharField(blank=True, max_length=100)),
                ('disability', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100)),
                ('specify', models.CharField(blank=True, max_length=200, null=True)),
                ('certify', models.BooleanField(blank=True, default=False)),
                ('parents_Name', models.CharField(blank=True, max_length=100)),
                ('addressp', models.CharField(blank=True, max_length=100)),
                ('phone_numberp', models.CharField(blank=True, max_length=100)),
                ('townp', models.CharField(blank=True, max_length=100)),
                ('lGAp', models.CharField(blank=True, max_length=100)),
                ('state_of_Originp', models.CharField(blank=True, max_length=100)),
                ('question_1', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100)),
                ('question_2', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100)),
                ('question_3', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100)),
                ('Admitted', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
