# Generated by Django 2.2 on 2022-12-21 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admission_form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='NewStudent',
        ),
    ]
