# Generated by Django 2.2 on 2022-12-21 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admission_form', '0003_admission_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admission_payment',
        ),
    ]
