# Generated by Django 2.2 on 2022-12-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admission_form', '0004_delete_admission_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newstudent',
            old_name='lGAp',
            new_name='Church',
        ),
        migrations.RenameField(
            model_name='newstudent',
            old_name='question_1',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='newstudent',
            old_name='state_of_Originp',
            new_name='Emailp',
        ),
        migrations.RenameField(
            model_name='newstudent',
            old_name='townp',
            new_name='MiddleName',
        ),
        migrations.RemoveField(
            model_name='newstudent',
            name='agg_Score',
        ),
        migrations.RemoveField(
            model_name='newstudent',
            name='common_Ent_Exam_Number',
        ),
        migrations.RemoveField(
            model_name='newstudent',
            name='question_2',
        ),
        migrations.RemoveField(
            model_name='newstudent',
            name='question_3',
        ),
        migrations.AddField(
            model_name='newstudent',
            name='gender',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
