# Generated by Django 2.2 on 2023-03-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admission_form', '0005_auto_20221229_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudent',
            name='Occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='newstudent',
            name='Comment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='newstudent',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
    ]
