# Generated by Django 2.2 on 2023-03-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admission_form', '0006_auto_20230308_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudent',
            name='Password',
            field=models.CharField(default='susgd', max_length=100),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='application_id',
            field=models.CharField(default='susgd', max_length=100),
        ),
    ]
