# Generated by Django 2.2 on 2023-03-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admission_form', '0008_auto_20230309_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstudent',
            name='Password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='newstudent',
            name='application_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
