# Generated by Django 2.2 on 2023-03-12 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0009_formteachers'),
        ('Attendance', '0001_initial'),
        ('Result_portal', '0008_students_pin_and_id_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='form_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.FormTeachers'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Result_portal.Students_Pin_and_ID'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
    ]
