# Generated by Django 2.2 on 2023-03-12 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0002_auto_20230312_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='deleted_at',
        ),
    ]
